console.log("Hello Winc Academy");
let name = "Marjolein";
console.log(name);
// You cannot make a variable with the name if
let sum = 3 + 4;
console.log("sum:", sum);
let sumWithStrings = "3" + "4";
console.log("sum with strings:", sumWithStrings);
let subtraction = 10 - 3;
console.log("subtraction:", subtraction);
let multiplication = 1483 * 6342;
console.log("multiplication:", multiplication);
let division = 12 / 3;
console.log("division:", division);
let modulus = 12 % 9;
console.log("modulus:", modulus);
let age = 48;
console.log(typeof age);
let ageAsString = "48";
console.log(typeof ageAsString);
